version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: iepure_MQ
    ports:
      - '5672:5672'
      - '15672:15672'
    
  ftp_server:
    image: 'stilliard/pure-ftpd:hardened'
    container_name: ftp_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      FTP_USER_NAME: testuser
      FTP_USER_PASS: testpass
      FTP_USER_HOME: /home/testuser
    volumes:
      - ./ftp_data:/home/testuser
    
  db:
    image: mysql:latest
    ports: 
      - "3207:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lab_db
      MYSQL_USER: lab_user
      MYSQL_PASSWORD: lab_password
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - lab_network

volumes:
  db_data:

networks:
  lab_network:
    driver: bridge
